### ISSUE TITLE
Fix for directory app in I.E.

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#43]

**Comment by piet0024** [comment]
Documenting some findings:
- There is a layout issue on the homepage for the bottom text block on IE
- on IE when clicking on the org chart, it loads for a moment and then crashes (more polyfill issues: `Object doesn't support property or method 'scrollTo'` and `Object doesn't support property or method 'repeat'`)

I'll update this comment with more.

**Comment by piet0024** [comment]
Update: Building and serving the app for production appears to fix some of these issues. Since we have made some changes to our dev environment (docker and k8s) for testing we may just need to make some small changes to the app build (instead of start, we will need to build and serve).

You will still run into these issues when developing the app in IE, so I will continue to look at this.

**Comment by piet0024** [comment]
https://github.com/gctools-outilsgc/directory-fe/pull/92

**Comment by piet0024** [comment]
https://github.com/gctools-outilsgc/directory-fe/pull/94
