### ISSUE TITLE
directory profile task flows

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/profile_service_react#9]

**Comment by amablex** [comment]
To @marianneaubrey15 and everybody else assigned to this task: it would great if we take some small amount of time to review the MVP interaction design document in detail since we would like to have some validation about this proposed direction we are heading design-wise. If we could do that between today and tomorrow, we can move forward with the next iteration on visual design to be made by @MPM9000.

Document link: https://gccollab.ca/file/download/1052536

**Comment by bryan-robitaille** [comment]
@amablex I took at the interaction design and I'm looking forward to the next iteration on the visual design.  Looking forward to here @piet0024 @alex-mes @DonnaMonbourquette @MPM9000 thoughts/comments
